---
title: "RAPID Fire Project - Lake Profile Data"
date: "2022-10-03"
author: "J. Brentrup"
output: html_notebook
---

# Load Libraries
```{r, message=FALSE}
library(tidyverse)
library(googledrive)
library(readxl)
```

# Download data
- load data directly from google drive folder
```{r, message=FALSE}

# See what files are available
drive_find(n_max=10)

# Download Lake Profiles Round 1
drive_download(as_id("13qx6D_9t2AW55z2Oqkfna_zNLHowxvh_"),
               path = "Data/Field Sampling_Lake Profiles_Round1.xlsx", 
               overwrite = TRUE)

# Download Lake Profiles Round 2
drive_download(as_id("1RR8g2oi-bJbWQ7zHIp60iSEFxtZ_wjgI"),
               path = "Data/Field Sampling_Lake Profiles_Round2.xlsx", 
               overwrite = TRUE)

```

# Load profile data
```{r}

profiles_may <- read_xlsx("Data/Field Sampling_Lake Profiles_Round1.xlsx", sheet = 1, col_types = c(
  ID = "numeric",
  Site = "text",
  Date = "date",
  Field2 = "logical",
 `Profile Depth (m)` = "numeric",
 `Water Temp (°C)` = "numeric",
`Spec Cond (µS/cm)` = "numeric",
`LDO (mg/L)` = "numeric",
`LDO %` = "numeric",
pH = "numeric",
Field1 = "logical"
  
))

str(profiles_may)

profiles_june <- read_xlsx("Data/Field Sampling_Lake Profiles_Round2.xlsx", sheet = 1, col_types = c(
  ID = "numeric",
  Site = "text",
  Date = "date",
  Field2 = "logical",
 `Profile Depth (m)` = "numeric",
 `Water Temp (°C)` = "numeric",
`Spec Cond (µS/cm)` = "numeric",
`LDO (mg/L)` = "numeric",
`LDO %` = "numeric",
pH = "numeric",
Field1 = "logical"
  
))

str(profiles_june)

```

# Check May data
```{r}
summary(profiles_may)

# Total number of lakes - 29
unique(profiles_may$Site)

#Filter for lakes > 2m - 11 lakes

deep_lakes <- profiles_may %>% 
  filter(`Profile Depth (m)` > 2) %>% 
  count(Site)

```

# Plot May water temp profiles
```{r}

# Deepest lake - 4th McDougal
deep_lake <- profiles_may %>% 
  filter(Site == "Fourth McDougal")

ggplot(data = deep_lake, aes(x = `Water Temp (°C)`, y = `Profile Depth (m)`)) +
  scale_y_reverse()+
  scale_x_continuous(position = "top")+
  geom_point()+
  geom_path()

# Filter for deep lakes (profiles > 2 m)
deep_lakes_profiles <- profiles_may %>% 
   filter(Site %in% deep_lakes$Site)

ggplot(data = deep_lakes_profiles, aes(x = `Water Temp (°C)`, y = `Profile Depth (m)`, color = Site)) +
  scale_y_reverse()+
  scale_x_continuous(position = "top")+
  geom_point()+
  geom_path()+
  facet_wrap(~Site)

```

