---
title: "Script to generate water quality boxplots"
author: "J. Brentrup"
date: '2022-10-26'
output:
  html_document:
    df_print: paged
    toc: true
editor_options:
  chunk_output_type: console
---

# Load Libraries
```{r, message=FALSE}
library(tidyverse)
library(googledrive)
library(readxl)
library(lubridate)
library(ggnewscale)
library(gridExtra)
```

# Load Data
### Water quality dataset for May-Sep 2022
```{r}
wq_data <- read_csv("Data/WaterQuality/combined_lab_field_may_sep.csv")
#str(wq_data)
summary(wq_data)

```

# Boxplot Code
### Order: TP, TN, DOC, pH, TSS, Chl-a, Secchi Depth, Water Temp
```{r}
# Create 2 color gradients for burn lakes (red) and control lakes (blue)

month_colors_red <- c("#bd0026", '#f03b20', "#fd8d3c", "#fecc5c", "#ffffb2") # red gradient
month_colors_blue <- c("#364b9a", '#5385bc', "#83b8d7", "#b7ddeb", "#eff3ff") # blue gradient


# Make factors for Group (Burn/Control & Isolated/Drainage) & Month
wq_data$Month_factor <- parse_factor(wq_data$Month_factor, levels = c("May","Jun","Jul","Aug","Sep"))
wq_data$Group <- parse_factor(wq_data$Group, levels = c("Burned_Drainage", "Control_Drainage", "Burned_Isolated", "Control_Isolated"))

# Add grouping variable for 2 different color schemes
wq_data <- wq_data %>% 
  mutate(color_group = ifelse(Group=="Burned_Drainage"|Group=="Burned_Isolated","group_red", "group_blue"))

# TP plot - order with Drainage lakes together 
range(wq_data$TP_ppb, na.rm = T)

TP_box <- ggplot(wq_data) +
  geom_boxplot(aes(x = Group, y = TP_ppb, fill = Month_factor), outlier.size = 1) + 
  scale_fill_manual(name = "Month", values=month_colors_red)+
  guides(fill = "none")+ #remove guide
  new_scale_fill()+ #allows you to set 2 different color scales
  geom_boxplot(aes(x = Group, y = TP_ppb, fill = Month_factor), filter(wq_data, color_group=="group_blue"), outlier.size = 1) + 
  scale_fill_manual(name = NULL, values=month_colors_blue)+
  guides(fill = "none")+ #remove guide
  theme_classic(base_size = 8) +
  labs(title = "a) TP", x = NULL, y = "Total Phosphorus (ppb)")+ #µg/L, x = "Lake Type"
  scale_y_continuous(limits=c(0,100))+
  scale_x_discrete(labels=c('BD','CD','BI','CI'))+ #scale_x_discrete(labels=c('BD','BI','CD','CI'))+
  theme(axis.title.x = element_text(size=8),
              axis.title.y = element_text(size=8),
              axis.text.y = element_text(size=8, color="black",margin = margin(l=5,r=3, unit = "pt")),
              axis.text.x = element_text(size=8, color="black",margin = margin(b=10,t=5, unit = "pt")),
              legend.title = element_text(size = 8),
              legend.position = c(0.1,0.8),#"top", puts legend on figure but covers outlier
              legend.text = element_text(size=8,color="black", margin = margin(r=7,l=5, unit = "pt")))+
        theme(axis.ticks.length = unit(.2, "cm"))

TP_box

# TP Plot - old order, burned lakes group vs. control group
# TP_box <- ggplot(wq_data) +
#   geom_boxplot(aes(x = Group, y = TP_ppb, fill = Month_factor), filter(wq_data, color_group=="group_red"), outlier.size = 1) + 
#   scale_fill_manual(name = "Month", values=month_colors_red)+
#  # guides(fill = "none")+ #remove guide
#   new_scale_fill()+ #allows you to set 2 different color scales
#   geom_boxplot(aes(x = Group, y = TP_ppb, fill = Month_factor), filter(wq_data, color_group=="group_blue"), outlier.size = 1) + 
#   scale_fill_manual(name = NULL, values=month_colors_blue)+
# #  guides(fill = "none")+ #remove guide
#   theme_classic(base_size = 8) +
#   labs(title = "A) TP", x = NULL, y = "Total Phosphorus (ppb)")+ #µg/L, x = "Lake Type"
#   #ggtitle("A) TP")+
#   scale_y_continuous(limits=c(0,100))+
#   scale_x_discrete(labels=c('BD','BI','CD','CI'))+
#   theme(axis.title.x = element_text(size=8),
#               axis.title.y = element_text(size=8),
#               axis.text.y = element_text(size=8, color="black",margin = margin(l=5,r=3, unit = "pt")),
#               axis.text.x = element_text(size=8, color="black",margin = margin(b=10,t=5, unit = "pt")),
#               legend.title = element_text(size = 8),
#               legend.position = c(0.1,0.8),#"right", puts legend on figure but covers outlier
#               legend.text = element_text(size=8,color="black", margin = margin(r=7,l=5, unit = "pt")))+
#         theme(axis.ticks.length = unit(.2, "cm"))


#TN
range(wq_data$TN_ppb, na.rm = T)

TN_box <- ggplot(wq_data) +
  geom_boxplot(aes(x = Group, y = TN_ppb, fill = Month_factor), outlier.size = 1) + #, filter(wq_data, color_group=="group_red")
  scale_fill_manual(name = "Month", values=month_colors_red)+
  guides(fill = "none")+ #remove guide
  new_scale_fill()+ #allows you to set 2 different color scales
  geom_boxplot(aes(x = Group, y = TN_ppb, fill = Month_factor), filter(wq_data, color_group=="group_blue"), outlier.size = 1) + 
  scale_fill_manual(name = NULL, values=month_colors_blue)+
  guides(fill = "none")+ #remove guide
  theme_classic(base_size = 8) +
  labs(title = "b) TN",x = NULL, y = "Total Nitrogen (ppb)")+ #µg/L
  scale_y_continuous(limits=c(200,1845), breaks=seq(200,1800,by=200))+
  scale_x_discrete(labels=c('BD','CD','BI','CI'))+
   theme(axis.title.x = element_text(size=8),
              axis.title.y = element_text(size=8),
              axis.text.y = element_text(size=8, color="black",margin = margin(l=5,r=3, unit = "pt")),
              axis.text.x = element_text(size=8, color="black",margin = margin(b=10,t=5, unit = "pt")),
              legend.title = element_text(size = 8),
              legend.position = c(0.1,0.8),#"right", puts legend on figure but covers outlier
              legend.text = element_text(size=8,color="black", margin = margin(r=7,l=5, unit = "pt")))+
        theme(axis.ticks.length = unit(.2, "cm"))

TN_box

#DOC
range(wq_data$DOC_ppm)

DOC_box <- ggplot(wq_data) +
  geom_boxplot(aes(x = Group, y = DOC_ppm, fill = Month_factor), outlier.size = 1) + #,  filter(wq_data, color_group=="group_red")
  scale_fill_manual(name = "Month", values=month_colors_red)+
  guides(fill = "none")+ #remove guide
  new_scale_fill()+ #allows you to set 2 different color scales
  geom_boxplot(aes(x = Group, y = DOC_ppm, fill = Month_factor), filter(wq_data, color_group=="group_blue"), outlier.size = 1) + 
  scale_fill_manual(name = NULL, values=month_colors_blue)+
  guides(fill = "none")+ #remove guide
  theme_classic(base_size = 8) +
  labs(title = "c) DOC",x = NULL, y = "Dissolved Organic Carbon (ppm)")+
  scale_y_continuous(limits=c(0,44), breaks=seq(0,40,by=10))+
  scale_x_discrete(labels=c('BD','CD','BI','CI'))+
  theme(axis.title.x = element_text(size=8),
              axis.title.y = element_text(size=8),
              axis.text.y = element_text(size=8, color="black",margin = margin(l=5,r=3, unit = "pt")),
              axis.text.x = element_text(size=8, color="black",margin = margin(b=10,t=5, unit = "pt")),
              legend.title = element_text(size = 8),
              legend.position = c(0.1,0.8),#"right", puts legend on figure but covers outlier
              legend.text = element_text(size=8,color="black", margin = margin(r=7,l=5, unit = "pt")))+
        theme(axis.ticks.length = unit(.2, "cm"))

DOC_box

 
#pH
range(wq_data$pH, na.rm = T)

pH_box <- ggplot(wq_data) +
  geom_boxplot(aes(x = Group, y = pH, fill = Month_factor), outlier.size = 1) + #, filter(wq_data, color_group=="group_red")
  scale_fill_manual(name = "Month", values=month_colors_red)+
  guides(fill = "none")+ #remove guide
  new_scale_fill()+ #allows you to set 2 different color scales
  geom_boxplot(aes(x = Group, y = pH, fill = Month_factor), filter(wq_data, color_group=="group_blue"), outlier.size = 1) + 
  scale_fill_manual(name = NULL, values=month_colors_blue)+
  guides(fill = "none")+ #remove guide
  theme_classic(base_size = 8) +
  labs(title = "d) pH",x = NULL, y = "pH")+
  scale_y_continuous(limits=c(5.5,9.5), breaks=seq(5.5,9.5, by=1))+
  scale_x_discrete(labels=c('BD','CD','BI','CI'))+
  theme(axis.title.x = element_text(size=8),
              axis.title.y = element_text(size=8),
              axis.text.y = element_text(size=8, color="black",margin = margin(l=5,r=3, unit = "pt")),
              axis.text.x = element_text(size=8, color="black",margin = margin(b=10,t=5, unit = "pt")),
              legend.title = element_text(size = 8),
              legend.position = "right", #c(0.1,0.8), puts legend on figure but covers outlier
              legend.text = element_text(size=8,color="black", margin = margin(r=7,l=5, unit = "pt")))+
        theme(axis.ticks.length = unit(.2, "cm"))

pH_box

#TSS
range(wq_data$TSS_mgL)

TSS_box <- ggplot(wq_data) +
  geom_boxplot(aes(x = Group, y = TSS_mgL, fill = Month_factor), outlier.size = 1) + #, filter(wq_data, color_group=="group_red")
  scale_fill_manual(name = "Month", values=month_colors_red)+
  guides(fill = "none")+ #remove guide
  new_scale_fill()+ #allows you to set 2 different color scales
  geom_boxplot(aes(x = Group, y = TSS_mgL, fill = Month_factor), filter(wq_data, color_group=="group_blue"), outlier.size = 1) + 
  scale_fill_manual(name = NULL, values=month_colors_blue)+
  guides(fill = "none")+ #remove guide
  theme_classic(base_size = 8) +
  labs(title = "e) TSS", x = NULL, y = "Total Suspended Solids (ppm)")+
  scale_y_continuous(limits=c(0,15), breaks=seq(0,15,by=5))+
  scale_x_discrete(labels=c('BD','CD','BI','CI'))+
  theme(axis.title.x = element_text(size=8),
              axis.title.y = element_text(size=8),
              axis.text.y = element_text(size=8, color="black",margin = margin(l=5,r=3, unit = "pt")),
              axis.text.x = element_text(size=8, color="black",margin = margin(b=10,t=5, unit = "pt")),
              legend.title = element_text(size = 8),
              legend.position = c(0.1,0.8),#"right", puts legend on figure but covers outlier
              legend.text = element_text(size=8,color="black", margin = margin(r=7,l=5, unit = "pt")))+
        theme(axis.ticks.length = unit(.2, "cm"))

TSS_box
 
#Chla
 range(wq_data$Chloro_ppb, na.rm = T)
 sum(is.na(wq_data$Chloro_ppb))

Chla_box <- ggplot(wq_data) +
  geom_boxplot(aes(x = Group, y = Chloro_ppb, fill = Month_factor), outlier.size = 1) + #, filter(wq_data, color_group=="group_red")
  scale_fill_manual(name = "Month", values=month_colors_red)+
  guides(fill = "none")+ #remove guide
  new_scale_fill()+ #allows you to set 2 different color scales
  geom_boxplot(aes(x = Group, y = Chloro_ppb, fill = Month_factor), filter(wq_data, color_group=="group_blue"), outlier.size = 1) + 
  scale_fill_manual(name = NULL, values=month_colors_blue)+
  guides(fill = "none")+ #remove guide
  theme_classic(base_size = 8) +
  labs(title = "f) Chlorophyll-a", x = NULL, y = "Chlorophyll-a (ppb)")+
  scale_y_continuous(limits=c(0,25.2), breaks=seq(0,25,by=5))+
  scale_x_discrete(labels=c('BD','CD','BI','CI'))+
  theme(axis.title.x = element_text(size=8),
              axis.title.y = element_text(size=8),
              axis.text.y = element_text(size=8, color="black",margin = margin(l=5,r=3, unit = "pt")),
              axis.text.x = element_text(size=8, color="black",margin = margin(b=10,t=5, unit = "pt")),
              legend.title = element_text(size = 8),
              legend.position = c(0.1,0.8),#"right", puts legend on figure but covers outlier
              legend.text = element_text(size=8,color="black", margin = margin(r=7,l=5, unit = "pt")))+
        theme(axis.ticks.length = unit(.2, "cm"))

Chla_box


#Secchi
 range(wq_data$SecchiDepth_m, na.rm = T)
 sum(is.na(wq_data$SecchiDepth_m))

Secchi_box <- ggplot(wq_data) +
  geom_boxplot(aes(x = Group, y = SecchiDepth_m, fill = Month_factor), outlier.size = 1) + #, filter(wq_data, color_group=="group_red")
  scale_fill_manual(name = "Month", values=month_colors_red)+
  guides(fill = "none")+ #remove guide
  new_scale_fill()+ #allows you to set 2 different color scales
  geom_boxplot(aes(x = Group, y = SecchiDepth_m, fill = Month_factor), filter(wq_data, color_group=="group_blue"), outlier.size = 1) + 
  scale_fill_manual(name = NULL, values=month_colors_blue)+
  guides(fill = "none")+ #remove guide
  theme_classic(base_size = 8) +
  labs(title = "g) Secchi Depth", x = NULL, y = "Secchi Depth (m)")+
  scale_y_continuous(limits=c(0,4.1), breaks=seq(0,4,by=1))+
  scale_x_discrete(labels=c('BD','CD','BI','CI'))+
   theme(axis.title.x = element_text(size=8),
              axis.title.y = element_text(size=8),
              axis.text.y = element_text(size=8, color="black",margin = margin(l=5,r=3, unit = "pt")),
              axis.text.x = element_text(size=8, color="black",margin = margin(b=10,t=5, unit = "pt")),
              legend.title = element_text(size = 8),
              legend.position = c(0.1,0.8),#"right", puts legend on figure but covers outlier
              legend.text = element_text(size=8,color="black", margin = margin(r=7,l=5, unit = "pt")))+
        theme(axis.ticks.length = unit(.2, "cm"))

Secchi_box

# Water Temp
range(wq_data$WaterTemp_C, na.rm = T)

WaterTemp_box <- ggplot(wq_data) +
  geom_boxplot(aes(x = Group, y = WaterTemp_C, fill = Month_factor), outlier.size = 1) + #, filter(wq_data, color_group=="group_red")
  scale_fill_manual(name = "Month", values=month_colors_red)+
  guides(fill = "none")+ #remove guide
  new_scale_fill()+ #allows you to set 2 different color scales
  geom_boxplot(aes(x = Group, y = WaterTemp_C, fill = Month_factor), filter(wq_data, color_group=="group_blue"), outlier.size = 1) + 
  scale_fill_manual(name = NULL, values=month_colors_blue)+
  guides(fill = "none")+ #remove guide
  theme_classic(base_size = 8) +
  labs(title = "h) Water Temperature", x = NULL, y = "Water Temperature (°C)")+
  scale_y_continuous(limits=c(8.5,27.5), breaks=seq(9,27,by=3))+
  scale_x_discrete(labels=c('BD','CD','BI','CI'))+
   theme(axis.title.x = element_text(size=8),
              axis.title.y = element_text(size=8),
              axis.text.y = element_text(size=8, color="black",margin = margin(l=5,r=3, unit = "pt")),
              axis.text.x = element_text(size=8, color="black",margin = margin(b=10,t=5, unit = "pt")),
              legend.title = element_text(size = 8),
              legend.position = "right", #c(0.1,0.8),"right", puts legend on figure but covers outlier
              legend.text = element_text(size=8,color="black", margin = margin(r=7,l=5, unit = "pt")))+
        theme(axis.ticks.length = unit(.2, "cm"))

WaterTemp_box
```

# Multipanel Figure
```{r}
# Multi-panel figure

grid.arrange(TP_box, TN_box, DOC_box,
             pH_box,TSS_box, Chla_box, Secchi_box, WaterTemp_box, ncol=2, nrow=4) # wide nrow = 2 #long ncol=2, nrow=4
```

# Save output of multi-panel figure
```{r}
# Save on github
# pdf("Figures/Multipanel_boxplot-long.pdf", width = 7.5, height = 9)
# 
# grid.arrange(TP_box, TN_box, DOC_box, pH_box,
#                 TSS_box, Chla_box, Secchi_box, WaterTemp_box, ncol=2, nrow=4)
# dev.off()

# Save locally
# jpeg("~/Documents/RAPID Fire Grant/Manuscript Figures/Multipanel_boxplot-long-nolegend.jpeg", width = 190, height = 230, units = 'mm',res=600)
# 
# jpeg("~/Documents/RAPID Fire Grant/Manuscript Figures/Multipanel_boxplot-wide-nolegend.jpeg", width = 230, height = 190, units = 'mm',res=600)
# 
# pdf("~/Documents/RAPID Fire Grant/Manuscript Figures/Multipanel_boxplot-long.pdf", width = 7.5, height = 9)
# 
# pdf("~/Documents/RAPID Fire Grant/Manuscript Figures/Multipanel_boxplot-wide.pdf", width = 9, height = 7.5)
# 
# 
 

```
